### GENERAL SETTINGS ###

# Site settings
title: <%= projectName %>
keywords: <%= projectKeywords %>
description: <%= projectDescription %>
tagline: <%= projectTagline %>
url: <%= cname %>

author:
  name: <%= authorName %>
  email: <%= authorEmail %>
  bio: <%= authorBio %>
  twitter: <%= authorTwitter %>
  
scss:
  style: compressed

nav:
- page: Home
  permalink: "#top"
  id: top
  icon: fa-home
  linktype: 1
  
- page: Section-1
  permalink: "#Section-1"
  id: why-link
  icon: fa-question-circle
  linktype: 1
  
- page: Section-2
  permalink: "#Section-2"
  id: overview-link
  icon: fa-star
  linktype: 1
  
- page: Section-3
  permalink: "#Section-3"
  id: started-link
  icon: fa-paper-plane
  linktype: 1
  
- page: Section-4
  permalink: "#Section-4"
  id: developers-link
  icon:  fa-code
  linktype: 1
 
- page: Section-5
  permalink: "#Section-5"
  id: blog-link
  icon: fa-rss
  linktype: 1
  
- page: Case Studies
  permalink: case-studies.html
  id: top-link
  icon:  fa-book
  linktype: 0

